// Generated by CoffeeScript 1.11.1
(function() {
  var Scissor, ScissorVoice, VirtualKeyboard, noteToFrequency;

  Scissor = (function() {
    function Scissor(context) {
      this.context = context;
      this.tuna = new Tuna(this.context);
      this.output = this.context.createGain();
      this.delay = new this.tuna.Delay({
        cutoff: 3000
      });
      this.delay.connect(this.output);
      this.voices = [];
      this.numSaws = 3;
      this.detune = 12;
    }

    Scissor.prototype.noteOn = function(note, time) {
      var freq, voice;
      if (this.voices[note] != null) {
        return;
      }
      if (time == null) {
        time = this.context.currentTime;
      }
      freq = noteToFrequency(note);
      voice = new ScissorVoice(this.context, freq, this.numSaws, this.detune);
      voice.connect(this.delay.input);
      voice.start(time);
      return this.voices[note] = voice;
    };

    Scissor.prototype.noteOff = function(note, time) {
      if (this.voices[note] == null) {
        return;
      }
      if (time == null) {
        time = this.context.currentTime;
      }
      this.voices[note].stop(time);
      return delete this.voices[note];
    };

    Scissor.prototype.connect = function(target) {
      return this.output.connect(target);
    };

    return Scissor;

  })();

  ScissorVoice = (function() {
    function ScissorVoice(context, frequency, numSaws1, detune1) {
      var i, j, ref, saw;
      this.context = context;
      this.frequency = frequency;
      this.numSaws = numSaws1;
      this.detune = detune1;
      this.output = this.context.createGain();
      this.maxGain = 1 / this.numSaws;
      this.attack = 0.001;
      this.decay = 0.015;
      this.release = 0.4;
      this.saws = [];
      for (i = j = 0, ref = this.numSaws; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
        saw = this.context.createOscillator();
        saw.type = 'sawtooth';
        saw.frequency.value = this.frequency;
        saw.detune.value = -this.detune + i * 2 * this.detune / (this.numSaws - 1);
        saw.start(this.context.currentTime);
        saw.connect(this.output);
        this.saws.push(saw);
      }
    }

    ScissorVoice.prototype.start = function(time) {
      this.output.gain.value = 0;
      this.output.gain.setValueAtTime(0, time);
      return this.output.gain.setTargetAtTime(this.maxGain, time + this.attack, this.decay + 0.001);
    };

    ScissorVoice.prototype.stop = function(time) {
      this.output.gain.cancelScheduledValues(time);
      this.output.gain.setValueAtTime(this.output.gain.value, time);
      this.output.gain.setTargetAtTime(0, time, this.release / 10);
      return this.saws.forEach((function(_this) {
        return function(saw) {
          return saw.stop(time + _this.release);
        };
      })(this));
    };

    ScissorVoice.prototype.connect = function(target) {
      return this.output.connect(target);
    };

    return ScissorVoice;

  })();

  VirtualKeyboard = (function() {
    function VirtualKeyboard($el, params) {
      var ref, ref1, ref2, ref3;
      this.$el = $el;
      this.lowestNote = (ref = params.lowestNote) != null ? ref : 48;
      this.letters = (ref1 = params.letters) != null ? ref1 : "awsedftgyhujkolpñ'".split('');
      this.noteOn = (ref2 = params.noteOn) != null ? ref2 : function(note) {
        return console.log("noteOn: " + note);
      };
      this.noteOff = (ref3 = params.noteOff) != null ? ref3 : function(note) {
        return console.log("noteOff: " + note);
      };
      this.keysPressed = {};
      this.render();
      this.bindKeys();
      this.bindMouse();
    }

    VirtualKeyboard.prototype._noteOn = function(note) {
      if (note in this.keysPressed) {
        return;
      }
      $(this.$el.find('li').get(note - this.lowestNote)).addClass('active');
      this.keysPressed[note] = true;
      return this.noteOn(note);
    };

    VirtualKeyboard.prototype._noteOff = function(note) {
      if (!(note in this.keysPressed)) {
        return;
      }
      $(this.$el.find('li').get(note - this.lowestNote)).removeClass('active');
      delete this.keysPressed[note];
      return this.noteOff(note);
    };

    VirtualKeyboard.prototype.bindKeys = function() {
      var fn, i, j, len, letter, ref;
      ref = this.letters;
      fn = (function(_this) {
        return function(letter, i) {
          Mousetrap.bind(letter, (function() {
            return _this._noteOn(_this.lowestNote + i);
          }), 'keydown');
          return Mousetrap.bind(letter, (function() {
            return _this._noteOff(_this.lowestNote + i);
          }), 'keyup');
        };
      })(this);
      for (i = j = 0, len = ref.length; j < len; i = ++j) {
        letter = ref[i];
        fn(letter, i);
      }
      Mousetrap.bind('z', (function(_this) {
        return function() {
          return _this.lowestNote -= 12;
        };
      })(this));
      return Mousetrap.bind('x', (function(_this) {
        return function() {
          return _this.lowestNote += 12;
        };
      })(this));
    };

    VirtualKeyboard.prototype.bindMouse = function() {
      return this.$el.find('li').each((function(_this) {
        return function(i, key) {
          $(key).mousedown(function() {
            return _this._noteOn(_this.lowestNote + i);
          });
          return $(key).mouseup(function() {
            return _this._noteOff(_this.lowestNote + i);
          });
        };
      })(this));
    };

    VirtualKeyboard.prototype.render = function() {
      var $key, $ul, i, j, len, letter, ref;
      this.$el.empty();
      $ul = $("<ul>");
      ref = this.letters;
      for (i = j = 0, len = ref.length; j < len; i = ++j) {
        letter = ref[i];
        $key = $("<li>" + letter + "</li>");
        if (i === 1 || i === 3 || i === 6 || i === 8 || i === 10 || i === 13 || i === 15) {
          $key.addClass('accidental');
        }
        $ul.append($key);
      }
      return this.$el.append($ul);
    };

    return VirtualKeyboard;

  })();

  noteToFrequency = function(note) {
    return Math.pow(2, (note - 69) / 12) * 440.0;
  };

  $(function() {
    var audioContext, detuneKnob, keyboard, masterGain, sawsKnob, setDetune, setNumSaws;
    audioContext = new (typeof AudioContext !== "undefined" && AudioContext !== null ? AudioContext : webkitAudioContext);
    masterGain = audioContext.createGain();
    masterGain.gain.value = 0.7;
    masterGain.connect(audioContext.destination);
    window.scissor = new Scissor(audioContext);
    scissor.connect(masterGain);
    keyboard = new VirtualKeyboard($("#keyboard"), {
      noteOn: function(note) {
        return scissor.noteOn(note);
      },
      noteOff: function(note) {
        return scissor.noteOff(note);
      }
    });
    setNumSaws = function(numSaws) {
      return scissor.numSaws = numSaws;
    };
    setDetune = function(detune) {
      return scissor.detune = detune;
    };
    sawsKnob = new Knob($("#saws")[0], new Ui.P2());
    sawsKnob.onChange = function(value) {
      return setNumSaws(value);
    };
    $("#saws").val(scissor.numSaws);
    sawsKnob.changed(0);
    detuneKnob = new Knob($("#detune")[0], new Ui.P2());
    detuneKnob.onChange = function(value) {
      return setDetune(value);
    };
    $("#detune").val(scissor.detune);
    return detuneKnob.changed(0);
  });

}).call(this);
